#! /bin/sh

# Workflow
sxhkd -m 1 &
xsetroot -cursor_name left_ptr &
feh --bg-scale --randomize /usr/share/backgrounds/landscapes/* &
xautolock -locker i3lock-fancy -time 10 &
setxkbmap -layout us,ru -option 'grp:caps_toggle' &
dunst &
picom --experimental-backends --config ~/.config/picom/picom.conf

~/.config/polybar/launch.sh &

# Tray
killall pa-applet
pa-applet &
caffeine &
blueman-applet &
nm-applet &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Smart gaps and border
bspc config single_monocle true
bspc config gapless_monocle true

#spotify
#bspc rule -a firefox-developer-edition desktop='^1'
#bspc rule -a code-insiders desktop='^2'
#bspc rule -a spotify desktop='^3'
